=== rodolfo53821/SiCopaTVD/programas/plugin eclipse/javatv_fcs/lib/JavaTVServiceFile.dtd
<?xml version="1.0" encoding="US-ASCII"?>

<!ELEMENT TestData (HEADING?,DataBundle+)>
<!ELEMENT Heading (#PCDATA)>
<!ELEMENT DataBundle (BundleDescription?,FavoriteService*,PreferredLanguage?, TransportStream*,Network*,Bouquet*,Xlet*,IPDatagram*,RatingDimension*,Service*,ServiceTransforms*,RemoveList*,RemoveSIDatabase*)*>
	<!ATTLIST DataBundle
		NAME ID #REQUIRED
	>
<!ELEMENT FavoriteService EMPTY>
	<!ATTLIST FavoriteService
		NAME CDATA #REQUIRED
		SERVICENAMES CDATA #REQUIRED
	>
<!ELEMENT IPDatagram EMPTY>
<!ELEMENT BundleDescription (#PCDATA)>
<!ELEMENT PreferredLanguage EMPTY>
	<!ATTLIST PreferredLanguage
		VALUE CDATA #REQUIRED
	>
<!ELEMENT RatingDimension (Rating)+>
	<!ATTLIST RatingDimension
		DIMENSIONNAME CDATA #REQUIRED
	>
<!ELEMENT Rating EMPTY>
	<!ATTLIST Rating
		NAME CDATA #REQUIRED
		DESCRIPTION CDATA #REQUIRED
	>
<!ELEMENT Service (ServiceDetails)?>
	<!ATTLIST Service
		NAME CDATA #REQUIRED
		SERVICETYPE CDATA #REQUIRED
		SITYPE CDATA #REQUIRED
		DESCRIPTION CDATA #IMPLIED
		SIMULATION CDATA #REQUIRED
		ALTERNATE CDATA #IMPLIED
		NUMBER CDATA #IMPLIED
		MINORNUMBER CDATA #IMPLIED
		CALIMIT CDATA #IMPLIED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT ServiceDetails (ProgramSchedule*,ServiceComponent*,ServiceComponentData*)*>
	<!ATTLIST ServiceDetails
		LONGNAME CDATA #REQUIRED
		PROVIDERNAME CDATA #REQUIRED
		DELIVERYSYSTEMTYPE CDATA #REQUIRED
		DESCRIPTION CDATA #IMPLIED
		CASYSTEMIDS CDATA #IMPLIED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT ProgramSchedule (ProgramEvent)*>
<!ELEMENT ProgramEvent (ContentRatingAdvisory*,ServiceComponent*,ServiceComponentData*)*>
	<!ATTLIST ProgramEvent
		NAME CDATA #REQUIRED
		DURATION CDATA #REQUIRED
		STARTTIME CDATA #REQUIRED
		DESCRIPTION CDATA #REQUIRED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT ServiceTransforms EMPTY> 
	<!ATTLIST ServiceTransforms
		NAME CDATA #REQUIRED
		LIST CDATA #REQUIRED
	>
<!ELEMENT ContentRatingAdvisory EMPTY>
	<!ATTLIST ContentRatingAdvisory
		DIMENSIONNAME CDATA #REQUIRED
		RATINGNAME CDATA #REQUIRED
		RATINGVALUE CDATA #IMPLIED
	>
<!ELEMENT ServiceComponent EMPTY>
	<!ATTLIST ServiceComponent
		NAME CDATA #REQUIRED
		LANGUAGE CDATA #REQUIRED
		STREAM_TYPE CDATA #REQUIRED
		AUTORUN CDATA #IMPLIED
		SIMULATION CDATA #IMPLIED
		ALTERNATE CDATA #IMPLIED
		CALIMIT CDATA #IMPLIED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT ServiceComponentData EMPTY>
	<!ATTLIST ServiceComponentData
		NAME CDATA #REQUIRED
		LANGUAGE CDATA #REQUIRED
		PATH CDATA #IMPLIED
		ARGS CDATA #IMPLIED
		AUTORUN CDATA #IMPLIED
		CALIMIT CDATA #IMPLIED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT TransportStream EMPTY>
	<!ATTLIST TransportStream
		ID CDATA #REQUIRED
		NAME CDATA #REQUIRED
		SITYPE CDATA #REQUIRED
		TRANSMITTIME CDATA #IMPLIED
		NETWORKID CDATA #IMPLIED
	>
<!ELEMENT Network EMPTY>
	<!ATTLIST Network
		ID CDATA #REQUIRED
		NAME CDATA #REQUIRED
		SITYPE CDATA #REQUIRED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT Bouquet EMPTY>
	<!ATTLIST Bouquet
		ID CDATA #REQUIRED
		NAME CDATA #REQUIRED
		SITYPE CDATA #REQUIRED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT Xlet EMPTY>
	<!ATTLIST Xlet
		NAME CDATA #REQUIRED
		PATH CDATA #REQUIRED
		ARGS CDATA #IMPLIED
		TRANSMITTIME CDATA #IMPLIED
	>
<!ELEMENT RemoveList (RemoveService*, RemoveProgramEvent*, RemoveBouquet*, 
	RemoveNetwork*, RemoveTransportStream*,
	RemoveServiceDetails*, RemoveServiceComponent*)*>

<!ELEMENT RemoveService EMPTY>
	<!ATTLIST RemoveService
		NAME CDATA #REQUIRED
		REASON CDATA #IMPLIED
	>
<!ELEMENT RemoveProgramEvent EMPTY>
	<!ATTLIST RemoveProgramEvent
		SERVICE_NAME CDATA #REQUIRED
		PROGRAM_NAME CDATA #REQUIRED
	>
<!ELEMENT RemoveBouquet EMPTY>
	<!ATTLIST RemoveBouquet
		ID CDATA #REQUIRED
	>
<!ELEMENT RemoveNetwork EMPTY>
	<!ATTLIST RemoveNetwork
		ID CDATA #REQUIRED
	>
<!ELEMENT RemoveTransportStream EMPTY>
	<!ATTLIST RemoveTransportStream
		ID CDATA #REQUIRED
	>
<!ELEMENT RemoveServiceDetails EMPTY>
	<!ATTLIST RemoveServiceDetails
		NAME CDATA #REQUIRED
	>
<!ELEMENT RemoveServiceComponent EMPTY>
	<!ATTLIST RemoveServiceComponent
		NAME CDATA #REQUIRED
	>
<!ELEMENT RemoveSIDatabase EMPTY>

=== rodolfo53821/SiCopaTVD/programas/plugin eclipse/javatv_fcs/lib/JavaTVSampleFile01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestData SYSTEM "JavaTVServiceFile.dtd">
   
<TestData>

   <DataBundle NAME="test1.1">

      <BundleDescription>
      </BundleDescription>
   
      <FavoriteService NAME="Duke's Favorites" SERVICENAMES="SERV1,SERV3"/>
      <FavoriteService NAME="Movie Specials"   SERVICENAMES="SERV4,SERV5,SERV13"/>
   
      <Bouquet NAME="TCK-PREMIUM-PACKAGE" ID="25" SITYPE="DVBSI"/>
      <Bouquet NAME="TBD-PREMIUM-PACKAGE" ID="26" SITYPE="DVBSI"/>
      <Bouquet NAME="WORLDGATE-PREMIUM-PACKAGE" ID="27" SITYPE="DVBSI" />
   
      <Network NAME="SERV1-COMPLETE" ID="12" SITYPE="DVBSI" />
      <Network NAME="SERV2-COMPLETE" ID="13" SITYPE="DVBSI" />
      <Network NAME="SERV3-COMPLETE" ID="11" SITYPE="DVBSI" />
   
      <TransportStream NAME="SERV1-COMPLETE"  ID="3" SITYPE="DVBSI" />
      <TransportStream NAME="SERV2-COMPLETE"  ID="4" SITYPE="DVBSI" />
      <TransportStream NAME="SERV3-BROADCAST" ID="5" SITYPE="DVBSI" NETWORKID ="11"/>
      <TransportStream NAME="SERV3-REGIONAL"  ID="6" SITYPE="DVBSI" NETWORKID ="11"/>
   
      <RatingDimension DIMENSIONNAME = "MPAA">
         <Rating NAME="G"     DESCRIPTION="General Audience" />
         <Rating NAME="PG"    DESCRIPTION="Parental Guidance" />
         <Rating NAME="PG-13" DESCRIPTION="Parental Guidance under 13" />
         <Rating NAME="R"     DESCRIPTION="Restricted" />
         <Rating NAME="X"     DESCRIPTION="No one under 21" />
         <Rating NAME="MA"    DESCRIPTION="Mature Audience" />
      </RatingDimension>
   
      <RatingDimension DIMENSIONNAME = "YAMPAA">
         <Rating NAME="A"   DESCRIPTION="Phoney desc for A" />
         <Rating NAME="B"   DESCRIPTION="Phoney desc for B" />
         <Rating NAME="C"   DESCRIPTION="Phoney desc for C" />
         <Rating NAME="D"   DESCRIPTION="Phoney desc for D" />
         <Rating NAME="E"   DESCRIPTION="Phoney desc for E" />
      </RatingDimension>
   
      <PreferredLanguage VALUE="heb" />
   
      <ServiceTransforms 
         NAME="SERV1-SERVICES" 
         LIST="SERV1,SERV5,SERV1-NEWS"/>

      <Service 
         NAME="SERV1-SERVICES" 
         SERVICETYPE="DIGITAL_TV" 
         SITYPE="DVBSI"
         DESCRIPTION="American Broadcasting"
         NUMBER="6" 
         MINORNUMBER="1"
         SIMULATION=""/>
   
      <Service 
         NAME="SERV1" 
         SERVICETYPE="DIGITAL_TV" 
         SITYPE="DVBSI"
         DESCRIPTION="American Broadcasting"
         NUMBER="6" 
         MINORNUMBER="1"
         CALIMIT="interrupt"
         SIMULATION="file:/c:/work/javatv/gatwick/data/lasco_c3.mpg">
   
         <ServiceDetails 
            PROVIDERNAME="TCK" 
            LONGNAME="American Broadcasting"
            DELIVERYSYSTEMTYPE="CABLE">
   
            <ProgramSchedule>

               <ProgramEvent 
                  NAME="SERV1 Evening News"
                  DURATION="120"
                  DESCRIPTION="Crisis in Yugoslavia"
                  STARTTIME="sysdate">
                  <ContentRatingAdvisory 
                     DIMENSIONNAME="MPAA" RATINGNAME="Mature Audience" />
                  <ContentRatingAdvisory 
                     DIMENSIONNAME="YAMPAA" RATINGNAME="Phoney desc for E"/>
               </ProgramEvent>

            </ProgramSchedule>
   
            <ServiceComponentData 
               NAME="Bug0000010" 
               LANGUAGE="ENGLISH"
               PATH="Bug0000010" 
               ARGS="arg0,arg1,arg2,arg3,arg4" />
   
            <ServiceComponentData 
               NAME="Bug4308104" 
               LANGUAGE="ENGLISH"
               PATH="Bug4308104" 
               ARGS="arg0,arg1,arg2,arg3,arg4" />

         </ServiceDetails>

      </Service>

      <Service 
         NAME="SERV2" 
         SERVICETYPE="DIGITAL_TV" 
         SITYPE="DVBSI"
         DESCRIPTION="Columbia Broadcasting"
         NUMBER="4" 
         MINORNUMBER="1"
         SIMULATION="file:/c:/work/javatv/gatwick/data/em-0002-01.mpg">
   
         <ServiceDetails PROVIDERNAME="TCK" 
            LONGNAME="Columbia Broadcasting"
            DELIVERYSYSTEMTYPE="CABLE">
   
         <ProgramSchedule>

            <ProgramEvent 
               NAME="SERV2 Daily News"
               DURATION="120"
               DESCRIPTION="Hint on progress in Washington DC"
               STARTTIME="sysdate">
               <ContentRatingAdvisory 
                  DIMENSIONNAME="MPAA" RATINGNAME="General Audience"/>
               <ContentRatingAdvisory 
                  DIMENSIONNAME="YAMPAA" RATINGNAME="Phoney desc for A"/>
            </ProgramEvent>
   
            <ProgramEvent 
               NAME="47 hours"
               DURATION="120"
               DESCRIPTION="Making fortune on the Internet" 
               STARTTIME="+120" />
   
            <ProgramEvent 
               NAME="That's not life"
               DURATION="120"
               DESCRIPTION="Melodrama of a mid-aged couple"
               STARTTIME="+240" />
   
            <ProgramEvent 
               NAME="66 seconds"
               DURATION="120"
               DESCRIPTION="Latest news on a tire crisis"
               STARTTIME="+360"
               TRANSMITTIME="+30" />
   
            <ProgramEvent 
               NAME="Survivant"
               DURATION="120"
               DESCRIPTION="And then there was one on the island"
               STARTTIME="+480"
               TRANSMITTIME="+45" />
   
            <ProgramEvent 
               NAME="Family Rules"
               DURATION="120"
               DESCRIPTION="The should and should not for a happy family" 
               STARTTIME="+600"
               TRANSMITTIME="+60" />
   
         </ProgramSchedule>
   
         <ServiceComponentData 
            NAME="Bug4308104" 
            LANGUAGE="ENGLISH"
            PATH="Bug4308104"
            ARGS="arg0,arg1,arg2,arg3,arg4" />
   
         </ServiceDetails>
   
      </Service>

      <Service 
         NAME="SERV3" 
         SERVICETYPE="DIGITAL_TV" 
         SITYPE="DVBSI"
         DESCRIPTION="National Broadcasting"
         NUMBER="5" 
         MINORNUMBER="1"
         SIMULATION="file:/c:/work/javatv/gatwick/data/em-0002-02.mpg">
   
         <ServiceDetails 
            PROVIDERNAME="TCK" 
            LONGNAME="National Broadcasting"
            DELIVERYSYSTEMTYPE="UNKNOWN">
   
            <ServiceComponentData 
               NAME="Bug4308104" 
               LANGUAGE="ENGLISH" 
               PATH="Bug4308104"
               ARGS="arg0,arg1,arg2,arg3,arg4" />

         </ServiceDetails>

      </Service>

      <Service 
         NAME="SERV4" 
         SERVICETYPE="DIGITAL_TV" 
         SITYPE="DVBSI"
         DESCRIPTION="International Broadcasting"
         NUMBER="3" 
         MINORNUMBER="1"
         SIMULATION="file:/c:/work/javatv/gatwick/data/em-0002-02.mpg">
   
         <ServiceDetails PROVIDERNAME="TCK" 
            LONGNAME="Funny Movies"
            DELIVERYSYSTEMTYPE="CABLE">
   
            <ProgramSchedule>
               <ProgramEvent NAME="There's Something About Martha"
                  DURATION="30"
                  DESCRIPTION="How to decorate your livingroom"
                  STARTTIME="sysdate" />
               <ProgramEvent NAME="Black Kitten, White Kitten"
                  DURATION="125"
                  DESCRIPTION="Anderay Tarkovsky's science fiction reality"
                  STARTTIME="+30" />
               <ProgramEvent 
                  NAME="Lock, Stock and two Smoked Barels"
                  DURATION="115"
                  DESCRIPTION="Giuseppe Tornatore's says what is a cinema for us"
                  STARTTIME="+155" />
               <ProgramEvent 
                  NAME="American Apple Cake"
                  DURATION="40"
                  DESCRIPTION="Teens hoping to get lucky before their highschool graduation"
                  STARTTIME="+270" />
               <ProgramEvent 
                  NAME="Recherche de Galaxie"
                  DURATION="60"
                  DESCRIPTION="Old TV stars regaining their pride though the galaxy quest"
                  STARTTIME="+310" />
            </ProgramSchedule>

         </ServiceDetails>

      </Service>

      <Service 
         NAME="SERV5" 
         SERVICETYPE="DIGITAL_TV" 
         SITYPE="DVBSI"
         DESCRIPTION="Walt D's Network"
         NUMBER="8" 
         MINORNUMBER="1"
         SIMULATION="file:/c:/work/javatv/gatwick/data/em-0002-02.mpg">
   
         <ServiceDetails PROVIDERNAME="TCK" 
            LONGNAME="Walt D's Network"
            DELIVERYSYSTEMTYPE="CABLE" />

      </Service>
      
      <Service 
         NAME="SERV6" 
         SERVICETYPE="DIGITAL_TV" SITYPE="DVBSI"
         DESCRIPTION="The Ultimate Sports Channel"
         NUMBER="12" 
         MINORNUMBER="1"
         SIMULATION="file:/c:/work/javatv/gatwick/data/lasco_c3.mpg"
         ALTERNATE="file:/c:/work/javatv/gatwick/data/orprobe1.mpg">
   
         <ServiceDetails 
            PROVIDERNAME="TCK" 
            LONGNAME="The Sports Network"
            DELIVERYSYSTEMTYPE="SATELLITE"
            DESCRIPTION="The Sports Network channel 12"
            CASYSTEMIDS="0,1">
   
            <ServiceComponent
               NAME="SERV6-VIDEO" 
               LANGUAGE="ENGLISH" 
               STREAM_TYPE="VIDEO"
               SIMULATION="file:/c:/work/javatv/gatwick/data/lasco_c3.mpg" />
   
            <ServiceComponent
               NAME="SERV6-AUDIO" 
               LANGUAGE="ENGLISH" 
               STREAM_TYPE="AUDIO"
               SIMULATION="file:/c:/work/javatv/gatwick/data/lasco_c3.mpg" />
   
            <ServiceComponent
               NAME="SERV6-SUBTITLES" 
               LANGUAGE="ENGLISH"
